### ISSUE TITLE
What is the purpose of feedgen?

### ISSUE THREAD

**Issue by 8ear** [coolacid/misp_feedgen#11]
Hi,
Why you wrote this tool?
What fix this tool?

**Comment by coolacid** [comment]
It generates files and feeds in different formats by pulling data from MISP. This can create CSV, Text and other file formatted reports, as well as the standard MISP feed file format.

**Comment by 8ear** [comment]
Ok so if I understand correct you create a feed from an misp instance to ingest it in other misp instance or to have a csv , text feed to ingest in other systems?

Thats really cool.

**Comment by 8ear** [comment]
Why is ssh and rsync included?

How it works? I understand from your read me that the generate.py generate only the cron file which must be then included, is that correct?

Should we integrate s6-overlay here? So that all works in one flow?

**Comment by coolacid** [comment]
ssh and rsync included because people generate files on one host and need to send it somewhere else?

generate.py will generate the outputs you configure in the configuration file. It should be run in a cronfile. 

I do not know what s6-overlay is.
